menu =('- Doces Finos\n'
        'Limão = R$320\n'
        'Ninho Trufado com Nutella = R$330\n'
        'Geleia de Morango = R$320\n'
        'Maracujá = R$320\n'
        'Pistache = R$340\n'
        'Physalis = R$340\n'
        'Brigadeiro Gourmet = R$330\n'
        'Caramelo Salgado = R$330\n'
        'Surpresa de Uva = R$250\n'
        'Cereja = R$340\n'
        'Camafeu de Nozes = R$340\n'
        'Creme Brulée com Nozes = R$330\n'
        'Ganache Branco com Morango = R$330\n'
        'Ganache ao Leite com Praline = R$330\n'
        'Trufa Meio Amarga = R$340\n'
        'Frutas Vermelhas = R$340\n'
        'Trufa de Coco = R$340\n'
         '\n'
        '- Brigadeiro Gourmet:\n'
        'Beijinho = R$180\n'
        'Leite Ninho = R$180\n'
        'Amendoim = R$180\n'
        'Bicho de Pé Morango = R$180\n'
        'Casadinho = R$180\n'
        'Tradicional com Amendoim = R$180\n'
        'Olho de Sogra Ameixa = R$180\n'
        'Damasco = R$180\n'
        'Creme Brulée = R$180\n'
        'Tradicional = R$190\n'
        'Churros = R$190\n'
        'Tradicional Dourado = R$190\n'
        'Ninho com Nutella = R$190\n'
        '\n'
        '- Mini Cupcakes:\n'
        'Mini Cupcakes Chantininho Glitter = R$4,50\n'
        'Mini Cupcakes Pasta Americana = R$5,40\n'
        'Mini Brownie = R$2,50\n'
        'Pirulito de Chocolate = R$7\n'
         '\n'
        '- Bolo Vulcão:\n'
        'Creme de Ninho P = R$27\n'
        'Creme de Ninho com Morango P = R$30\n'
        'Creme de Ninho com Nutella P = R$35\n'
        'Creme de Ninho G = R$55\n'
        'Creme de Ninho com Morango G = R$60\n'
        'Creme de Ninho com Nutella G = R$70\n'
        '\n'
        )
